sudo: false
language: node_js
dist: xenial

services:
  - xvfb

addons:
  chrome: stable

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

node_js:
  - 14.15.4

script: lerna run build && lerna run min && lerna run test:ci
